# baseURL
@baseURL = http://localhost:3000


###
# Get All User
GET {{ baseURL }}/users
Content-Type: application/json

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
    "username": "ardiwinardi",
    "password": "secret"
}

###
# Update User
PUT {{ baseURL }}/users/qwertytyuyi
Content-Type: application/json

{
    "name": "ardiwinardi"
}

###
# Delete User
DELETE {{ baseURL }}/users/qwuyetquwyetu
Content-Type: application/json
